#ifndef DEFINE
#define DEFINE

// DOZEN pins
#define DOZEN1_PORT   GPIOB
#define DOZEN1_PIN    GPIO_Pin_10
#define DOZEN1_ON     DOZEN1_PORT->BRR |= DOZEN1_PIN
#define DOZEN1_OFF    DOZEN1_PORT->BSRR |= DOZEN1_PIN

#define DOZEN2_PORT   GPIOB
#define DOZEN2_PIN    GPIO_Pin_11
#define DOZEN2_ON     DOZEN2_PORT->BRR |= DOZEN2_PIN
#define DOZEN2_OFF    DOZEN2_PORT->BSRR |= DOZEN2_PIN

#define DOZEN3_PORT   GPIOB
#define DOZEN3_PIN    GPIO_Pin_12
#define DOZEN3_ON     DOZEN3_PORT->BRR |= DOZEN3_PIN
#define DOZEN3_OFF    DOZEN3_PORT->BSRR |= DOZEN3_PIN

#define DOZEN4_PORT   GPIOB
#define DOZEN4_PIN    GPIO_Pin_13
#define DOZEN4_ON     DOZEN4_PORT->BRR |= DOZEN4_PIN
#define DOZEN4_OFF    DOZEN4_PORT->BSRR |= DOZEN4_PIN

#define DOZEN5_PORT   GPIOB
#define DOZEN5_PIN    GPIO_Pin_14
#define DOZEN5_ON     DOZEN5_PORT->BRR |= DOZEN5_PIN
#define DOZEN5_OFF    DOZEN5_PORT->BSRR |= DOZEN5_PIN

#define DOZEN6_PORT   GPIOB
#define DOZEN6_PIN    GPIO_Pin_15
#define DOZEN6_ON     DOZEN6_PORT->BRR |= DOZEN6_PIN
#define DOZEN6_OFF    DOZEN6_PORT->BSRR |= DOZEN6_PIN

#define DOZEN7_PORT   GPIOC
#define DOZEN7_PIN    GPIO_Pin_9
#define DOZEN7_ON     DOZEN7_PORT->BRR |= DOZEN7_PIN
#define DOZEN7_OFF    DOZEN7_PORT->BSRR |= DOZEN7_PIN

#define DOZEN8_PORT   GPIOC
#define DOZEN8_PIN    GPIO_Pin_8
#define DOZEN8_ON     DOZEN8_PORT->BRR |= DOZEN8_PIN
#define DOZEN8_OFF    DOZEN8_PORT->BSRR |= DOZEN8_PIN

#define DOZEN9_PORT   GPIOC
#define DOZEN9_PIN    GPIO_Pin_12
#define DOZEN9_ON     DOZEN9_PORT->BRR |= DOZEN9_PIN
#define DOZEN9_OFF    DOZEN9_PORT->BSRR |= DOZE9_PIN

#define DOZEN10_PORT   GPIOC
#define DOZEN10_PIN    GPIO_Pin_11
#define DOZEN10_ON     DOZEN10_PORT->BRR |= DOZEN10_PIN
#define DOZEN10_OFF    DOZEN10_PORT->BSRR |= DOZEN10_PIN

#define DOZEN11_PORT   GPIOC
#define DOZEN11_PIN    GPIO_Pin_10
#define DOZEN11_ON     DOZEN11_PORT->BRR |= DOZEN11_PIN
#define DOZEN11_OFF    DOZEN11_PORT->BSRR |= DOZEN11_PIN

#define DOZEN12_PORT   GPIOC
#define DOZEN12_PIN    GPIO_Pin_5
#define DOZEN12_ON     DOZEN12_PORT->BRR |= DOZEN12_PIN
#define DOZEN12_OFF    DOZEN12_PORT->BSRR |= DOZEN12_PIN

// ARCDOZEN
#define ARCDOZEN1_PORT   GPIOB
#define ARCDOZEN1_PIN    GPIO_Pin_1
#define ARCDOZEN1_PWM(x) TIM_SetCompare4(TIM3, x)

#define ARCDOZEN2_PORT   GPIOB
#define ARCDOZEN2_PIN    GPIO_Pin_0
#define ARCDOZEN2_PWM(x) TIM_SetCompare3(TIM3, x)

#define ARCDOZEN3_PORT   GPIOA
#define ARCDOZEN3_PIN    GPIO_Pin_3
#define ARCDOZEN3_PWM(x) TIM_SetCompare4(TIM2, x)

#define ARCDOZEN4_PORT   GPIOA
#define ARCDOZEN4_PIN    GPIO_Pin_2
#define ARCDOZEN4_PWM(x) TIM_SetCompare3(TIM2, x)

#define ARCDOZEN5_PORT   GPIOA
#define ARCDOZEN5_PIN    GPIO_Pin_1
#define ARCDOZEN5_PWM(x) TIM_SetCompare2(TIM2, x)

#define ARCDOZEN6_PORT   GPIOA
#define ARCDOZEN6_PIN    GPIO_Pin_0
#define ARCDOZEN6_PWM(x) TIM_SetCompare1(TIM2, x)

#define ARCDOZEN7_PORT   GPIOB
#define ARCDOZEN7_PIN    GPIO_Pin_9
#define ARCDOZEN7_PWM(x) TIM_SetCompare4(TIM4, x)

#define ARCDOZEN8_PORT   GPIOB
#define ARCDOZEN8_PIN    GPIO_Pin_8
#define ARCDOZEN8_PWM(x) TIM_SetCompare3(TIM4, x)

#define ARCDOZEN9_PORT   GPIOB
#define ARCDOZEN9_PIN    GPIO_Pin_7
#define ARCDOZEN9_PWM(x) TIM_SetCompare2(TIM4, x)

#define ARCDOZEN10_PORT   GPIOB
#define ARCDOZEN10_PIN    GPIO_Pin_6
#define ARCDOZEN10_PWM(x) TIM_SetCompare1(TIM4, x)

// Let op REMAP, Check partial remap mogelijk
#define ARCDOZEN11_PORT   GPIOC
#define ARCDOZEN11_PIN    GPIO_Pin_7
#define ARCDOZEN11_PWM(x) TIM_SetCompare2(TIM3, x)

#define ARCDOZEN12_PORT   GPIOC
#define ARCDOZEN12_PIN    GPIO_Pin_6
#define ARCDOZEN12_PWM(x) TIM_SetCompare1(TIM3, x)

#endif
